apiVersion: apps/v1
kind: Deployment
metadata:
  name: dietfit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dietfit
  template:
    metadata:
      labels:
        app: dietfit
    spec:
      containers:
        - name: dietfit
          image: muneeb6774/dietfit:latest
          ports:
            - containerPort: 8082
